'use client';

import React, { useState, useEffect } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { useAuth } from '@/contexts/AuthContext';
import { supabase } from '@/lib/supabase';
import {
  ArrowLeftIcon,
  PlusIcon,
  TrashIcon,
  CheckCircleIcon,
  InformationCircleIcon,
} from '@heroicons/react/24/outline';

// Types
interface LineItem {
  id: string;
  category: string;
  description: string;
  specs?: string;
  quantity: number;
  unit: string;
  pricePerUnit: number;
  isAutoGenerated: boolean;
  isCustom?: boolean;
  isClientSelected?: boolean; // true = client explicitly selected this in checklist
}

interface EventData {
  id: string;
  title: string;
  client_brief: {
    event_type: string;
    date: string;
    city: string;
    guest_count: number;
    venue_status: string;
    checklist?: {
      selections: Record<string, any>;
      categoryNotes: Record<string, string>;
    };
  };
  forge_blueprint: {
    sections: Array<{
      id: string;
      title: string;
      items: any[];
    }>;
  };
}

export default function SmartBidTemplate() {
  const params = useParams();
  const router = useRouter();
  const eventId = params.eventId as string;
  const { user, isAuthenticated, isLoading: authLoading, isVendor } = useAuth();

  const [event, setEvent] = useState<EventData | null>(null);
  const [loading, setLoading] = useState(true);
  const [lineItems, setLineItems] = useState<LineItem[]>([]);
  const [categoryNotes, setCategoryNotes] = useState<Record<string, string>>({});
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    if (authLoading) return;

    if (!isAuthenticated || !isVendor) {
      router.push(`/craftsmen/login?returnUrl=/craftsmen/events/${eventId}/bid`);
      return;
    }

    loadEventAndGenerateLineItems();
  }, [authLoading, isAuthenticated, isVendor, eventId]);

  const loadEventAndGenerateLineItems = async () => {
    try {
      setLoading(true);
      const response = await fetch(`/api/forge/projects/${eventId}`);
      const data = await response.json();

      if (!data.success || !data.event) {
        console.error('Failed to load event');
        setLoading(false);
        return;
      }

      setEvent(data.event);
      const generatedItems = autoGenerateLineItems(data.event);
      setLineItems(generatedItems);
      setLoading(false);
    } catch (error) {
      console.error('Error loading event:', error);
      setLoading(false);
    }
  };

  // Helper function to create a line item with smart quantity calculation
  const createLineItem = (description: string, categoryName: string, guestCount: number, sectionId: string, itemId: string): LineItem => {
    let quantity = 1;
    let unit = 'package';

    // Smart quantity calculation based on description
    const descLower = description.toLowerCase();

    if (descLower.includes('chair') || descLower.includes('seat')) {
      quantity = guestCount;
      unit = 'piece';
    } else if (descLower.includes('table')) {
      quantity = Math.ceil(guestCount / 10); // 10 people per table
      unit = 'piece';
    } else if (descLower.includes('plate') || descLower.includes('meal') || descLower.includes('serving')) {
      quantity = guestCount;
      unit = 'plate';
    } else if (descLower.includes('buffet counter')) {
      quantity = Math.ceil(guestCount / 100);
      unit = 'counter';
    } else if (descLower.includes('staff') || descLower.includes('server')) {
      quantity = Math.ceil(guestCount / 25);
      unit = 'person';
    } else if (descLower.includes('drink') || descLower.includes('beverage') || descLower.includes('mocktail')) {
      quantity = guestCount;
      unit = 'glass';
    } else if (descLower.includes('package') || descLower.includes('theme') || descLower.includes('decor')) {
      quantity = 1;
      unit = 'package';
    } else if (descLower.includes('lighting') || descLower.includes('sound')) {
      quantity = 1;
      unit = 'set';
    }

    return {
      id: `auto-${sectionId}-${itemId}-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      category: categoryName,
      description: description,
      quantity: quantity,
      unit: unit,
      pricePerUnit: 0,
      isAutoGenerated: true,
    };
  };

  const autoGenerateLineItems = (eventData: EventData): LineItem[] => {
    const items: LineItem[] = [];
    const clientBrief = eventData.client_brief;
    const blueprint = eventData.forge_blueprint;
    const guestCount = clientBrief.guest_count || 0;
    const checklistSelections = clientBrief.checklist?.selections || {};

    console.log('[Smart Bid] Generating line items from blueprint:', blueprint);
    console.log('[Smart Bid] Checklist selections:', checklistSelections);
    console.log('[Smart Bid] Blueprint has sections?', blueprint?.sections);
    console.log('[Smart Bid] Blueprint sections array?', Array.isArray(blueprint?.sections));

    // Generate line items for ALL blueprint items.
    // Items the client selected get their selection as the description (highlighted).
    // Items the client didn't select still appear so the vendor can price them if relevant.
    if (blueprint && blueprint.sections && Array.isArray(blueprint.sections)) {
      blueprint.sections.forEach((section) => {
        const categoryName = section.title || 'General';

        if (section.items && Array.isArray(section.items)) {
          section.items.forEach((item: any, index: number) => {
            const itemId = item.id;
            const itemSelection = checklistSelections[itemId];
            const isClientSelected = !!(itemSelection && (Array.isArray(itemSelection) ? itemSelection.length > 0 : true));

            if (isClientSelected && Array.isArray(itemSelection)) {
              // Multi-select: one line item per chosen value
              itemSelection.forEach((selectedValue: string) => {
                const lineItem = createLineItem(selectedValue || item.label || item.description || `Item ${index + 1}`, categoryName, guestCount, section.id, itemId);
                items.push({ ...lineItem, isClientSelected: true });
              });
            } else if (isClientSelected) {
              // Single selection: use the client's answer as the description
              const description = String(itemSelection) || item.label || item.description || `Item ${index + 1}`;
              const lineItem = createLineItem(description, categoryName, guestCount, section.id, item.id || index.toString());
              items.push({ ...lineItem, isClientSelected: true });
            } else {
              // Not selected by client — include as an optional line item with the blueprint label
              const description = item.label || item.description || `Item ${index + 1}`;
              items.push({
                id: `auto-${section.id}-${itemId}-${Date.now()}-${Math.random().toString(36).substr(2, 5)}`,
                category: categoryName,
                description,
                quantity: 1,
                unit: 'package',
                pricePerUnit: 0,
                isAutoGenerated: true,
                isClientSelected: false,
              });
            }
          });
        }
      });
    }

    console.log('[Smart Bid] Generated items:', items.length, 'items');

    // If no items were generated from blueprint, fall back to basic items
    if (items.length === 0) {
      console.log('[Smart Bid] No blueprint items found, using fallback items');

      // Basic seating
      if (guestCount > 0) {
        items.push({
          id: `auto-chairs-${Date.now()}`,
          category: 'Foundation Specifications',
          description: 'Chairs',
          quantity: guestCount,
          unit: 'piece',
          pricePerUnit: 0,
          isAutoGenerated: true,
        });

        items.push({
          id: `auto-tables-${Date.now()}`,
          category: 'Foundation Specifications',
          description: 'Tables (10-seater)',
          quantity: Math.ceil(guestCount / 10),
          unit: 'piece',
          pricePerUnit: 0,
          isAutoGenerated: true,
        });
      }

      // Basic decorations
      items.push({
        id: `auto-decoration-${Date.now()}`,
        category: 'Decorations',
        description: `${clientBrief.event_type} Theme Decoration Package`,
        quantity: 1,
        unit: 'package',
        pricePerUnit: 0,
        isAutoGenerated: true,
      });
    }

    return items;
  };

  const updateLineItem = (id: string, updates: Partial<LineItem>) => {
    setLineItems((prev) =>
      prev.map((item) => (item.id === id ? { ...item, ...updates } : item))
    );
  };

  const removeLineItem = (id: string) => {
    setLineItems((prev) => prev.filter((item) => item.id !== id));
  };

  const addCustomLineItem = (category: string) => {
    const newItem: LineItem = {
      id: `custom-${Date.now()}`,
      category,
      description: '',
      quantity: 1,
      unit: 'package',
      pricePerUnit: 0,
      isAutoGenerated: false,
      isCustom: true,
    };
    setLineItems((prev) => [...prev, newItem]);
  };

  const calculateSubtotal = (): number => {
    return lineItems.reduce(
      (sum, item) => sum + item.quantity * item.pricePerUnit,
      0
    );
  };

  const calculateGST = (): number => {
    return calculateSubtotal() * 0.18;
  };

  const calculateTotal = (): number => {
    return calculateSubtotal() + calculateGST();
  };

  const handleSubmit = async () => {
    console.log('[Smart Bid] ========================================');
    console.log('[Smart Bid] SUBMIT BUTTON CLICKED');
    console.log('[Smart Bid] ========================================');
    setSubmitting(true);

    try {
      console.log('[Smart Bid] Step 1: Getting Supabase session...');
      // Get Supabase auth token
      const { data: { session }, error: sessionError } = await supabase.auth.getSession();
      console.log('[Smart Bid] Session result:', { hasSession: !!session, error: sessionError });

      if (sessionError || !session) {
        console.error('[Smart Bid] No active session:', sessionError);
        alert('Authentication error. Please log in again.');
        router.push('/craftsmen/login');
        setSubmitting(false);
        return;
      }

      console.log('[Smart Bid] Step 2: Preparing bid data...');
      console.log('[Smart Bid] Event ID:', eventId);
      console.log('[Smart Bid] Vendor ID:', user?.userId);
      console.log('[Smart Bid] Line items count:', lineItems.length);

      const bidData = {
        event_id: eventId,
        vendor_id: user?.userId,
        forge_items: lineItems.map((item) => ({
          name: item.description,
          description: item.description,
          specs: item.specs || '',
          quantity: item.quantity,
          unit: item.unit,
          unitPrice: item.pricePerUnit,
          lineTotal: item.quantity * item.pricePerUnit,
          category: item.category,
          isAutoGenerated: item.isAutoGenerated,
          isCustom: item.isCustom,
        })),
        craft_specialties: [...new Set(lineItems.map((item) => item.category))],
        subtotal: calculateSubtotal(),
        taxes: calculateGST(),
        total_forge_cost: calculateTotal(),
        vendor_notes: Object.entries(categoryNotes)
          .map(([cat, note]) => `${cat}: ${note}`)
          .join('\n\n'),
        estimated_forge_time: '14 days',
      };

      console.log('[Smart Bid] Step 3: Sending POST request to /api/bids...');
      console.log('[Smart Bid] Bid data:', JSON.stringify(bidData, null, 2));

      const response = await fetch('/api/bids', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${session.access_token}`,
        },
        body: JSON.stringify(bidData),
      });

      console.log('[Smart Bid] Step 4: Response received:', {
        status: response.status,
        ok: response.ok,
        statusText: response.statusText
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({ error: 'Failed to submit bid' }));
        console.error('[Smart Bid] Submit error:', errorData);
        throw new Error(errorData.error || 'Failed to submit bid');
      }

      console.log('[Smart Bid] Step 5: Parsing response...');
      const result = await response.json();
      console.log('[Smart Bid] Bid submitted successfully:', result);

      alert('Bid submitted successfully!');
      router.push('/craftsmen/dashboard');
    } catch (error) {
      console.error('[Smart Bid] Error submitting bid:', error);
      alert(error instanceof Error ? error.message : 'Failed to submit bid. Please try again.');
    } finally {
      setSubmitting(false);
    }
  };

  if (loading || !event) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-blue-900 flex items-center justify-center">
        <div className="text-center">
          <div className="w-16 h-16 border-4 border-orange-500 border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
          <p className="text-slate-300">Loading smart bid template...</p>
        </div>
      </div>
    );
  }

  const categories = [...new Set(lineItems.map((item) => item.category))];

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-blue-900">
      {/* Header */}
      <div className="bg-slate-800/50 backdrop-blur-sm border-b border-slate-700 sticky top-0 z-10">
        <div className="max-w-[1600px] mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-4">
              <button
                onClick={() => router.push('/craftsmen/dashboard')}
                className="p-2 hover:bg-slate-700 rounded-lg transition-colors"
              >
                <ArrowLeftIcon className="w-5 h-5 text-slate-300" />
              </button>
              <div>
                <h1 className="text-xl font-bold text-white">
                  Smart Bid Template
                </h1>
                <p className="text-sm text-slate-400">{event.title}</p>
              </div>
            </div>
            <button
              onClick={handleSubmit}
              disabled={submitting}
              className="px-6 py-3 bg-gradient-to-r from-orange-500 to-orange-600 hover:from-orange-600 hover:to-orange-700 text-white font-semibold rounded-lg transition-all duration-200 disabled:opacity-50"
            >
              {submitting ? 'Submitting...' : 'Submit Proposal'}
            </button>
          </div>
        </div>
      </div>

      {/* Three-panel layout */}
      <div className="max-w-[1600px] mx-auto p-6">
        <div className="grid grid-cols-12 gap-6">
          {/* LEFT PANEL - Client Requirements (Read-Only) */}
          <div className="col-span-3 space-y-4">
            <div className="bg-slate-800/50 backdrop-blur-sm rounded-xl border border-slate-700 p-6 sticky top-24">
              <h2 className="text-lg font-bold text-white mb-4 flex items-center">
                <InformationCircleIcon className="w-5 h-5 mr-2 text-blue-400" />
                Client Requirements
              </h2>

              <div className="space-y-3 text-sm">
                <div>
                  <p className="text-slate-400">Event Type</p>
                  <p className="text-white font-medium capitalize">
                    {event.client_brief.event_type}
                  </p>
                </div>
                <div>
                  <p className="text-slate-400">Date</p>
                  <p className="text-white font-medium">
                    {new Date(event.client_brief.date).toLocaleDateString()}
                  </p>
                </div>
                <div>
                  <p className="text-slate-400">Location</p>
                  <p className="text-white font-medium">
                    {event.client_brief.city}
                  </p>
                </div>
                <div>
                  <p className="text-slate-400">Guest Count</p>
                  <p className="text-white font-medium">
                    {event.client_brief.guest_count} guests
                  </p>
                </div>
                <div>
                  <p className="text-slate-400">Venue Status</p>
                  <p className="text-white font-medium capitalize">
                    {event.client_brief.venue_status?.replace('_', ' ')}
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* CENTER PANEL - Line Items (Editable) */}
          <div className="col-span-6 space-y-6">
            {categories.map((category) => {
              const categoryItems = lineItems.filter(
                (item) => item.category === category
              );

              return (
                <div
                  key={category}
                  className="bg-slate-800/50 backdrop-blur-sm rounded-xl border border-slate-700 p-6"
                >
                  <h3 className="text-lg font-bold text-white mb-4">
                    {category}
                  </h3>

                  <div className="space-y-3">
                    {/* Header */}
                    <div className="grid grid-cols-12 gap-2 text-xs text-slate-400 font-medium px-2">
                      <div className="col-span-4">Description</div>
                      <div className="col-span-2 text-center">Quantity</div>
                      <div className="col-span-2 text-center">Unit</div>
                      <div className="col-span-2 text-right">Price/Unit</div>
                      <div className="col-span-1 text-right">Total</div>
                      <div className="col-span-1"></div>
                    </div>

                    {/* Line Items */}
                    {categoryItems.map((item) => (
                      <div
                        key={item.id}
                        className={`grid grid-cols-12 gap-2 items-center p-2 rounded-lg border-l-4 ${
                          item.isClientSelected
                            ? 'bg-orange-500/10 border-orange-500'
                            : 'bg-slate-900/50 border-slate-700'
                        }`}
                      >
                        {/* Badge row above inputs */}
                        <div className="col-span-12 flex items-center gap-2 mb-1">
                          {item.isClientSelected ? (
                            <span className="text-xs font-semibold text-orange-400 flex items-center gap-1">
                              <CheckCircleIcon className="w-3 h-3" /> Client Request
                            </span>
                          ) : (
                            <span className="text-xs text-slate-500 italic">Optional — not selected by client</span>
                          )}
                        </div>
                        <div className="col-span-4 flex flex-col gap-1">
                          <input
                            type="text"
                            value={item.description}
                            onChange={(e) =>
                              updateLineItem(item.id, {
                                description: e.target.value,
                              })
                            }
                            className="bg-slate-700 px-3 py-2 rounded text-sm text-white"
                            placeholder="Item description"
                          />
                          <input
                            type="text"
                            value={item.specs || ''}
                            onChange={(e) =>
                              updateLineItem(item.id, { specs: e.target.value })
                            }
                            className="bg-slate-600 px-3 py-1.5 rounded text-xs text-slate-300 placeholder-slate-500"
                            placeholder="Dimensions, materials, finish — optional"
                          />
                        </div>

                        <input
                          type="number"
                          value={item.quantity}
                          onChange={(e) =>
                            updateLineItem(item.id, {
                              quantity: parseInt(e.target.value) || 0,
                            })
                          }
                          className="col-span-2 bg-slate-700 px-3 py-2 rounded text-sm text-white text-center [appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none"
                        />

                        <select
                          value={item.unit}
                          onChange={(e) =>
                            updateLineItem(item.id, { unit: e.target.value })
                          }
                          className="col-span-2 bg-slate-700 px-3 py-2 rounded text-sm text-white"
                        >
                          <option value="package">package</option>
                          <option value="piece">piece</option>
                          <option value="hour">hour</option>
                          <option value="day">day</option>
                          <option value="person">person</option>
                          <option value="set">set</option>
                          <option value="counter">counter</option>
                        </select>

                        <div className="col-span-2 flex items-center">
                          <span className="text-slate-400 mr-1 text-sm">₹</span>
                          <input
                            type="number"
                            value={item.pricePerUnit}
                            onChange={(e) =>
                              updateLineItem(item.id, {
                                pricePerUnit: parseFloat(e.target.value) || 0,
                              })
                            }
                            className="w-full bg-slate-700 px-3 py-2 rounded text-sm text-white text-right [appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none"
                            placeholder="0"
                          />
                        </div>

                        <div className="col-span-1 text-right font-semibold text-orange-400 text-sm pr-2">
                          ₹
                          {(item.quantity * item.pricePerUnit).toLocaleString(
                            'en-IN'
                          )}
                        </div>

                        <button
                          onClick={() => removeLineItem(item.id)}
                          className="col-span-1 text-red-400 hover:text-red-300 transition-colors flex items-center justify-center"
                        >
                          <TrashIcon className="w-4 h-4" />
                        </button>
                      </div>
                    ))}

                    {/* Add Custom Item */}
                    <button
                      onClick={() => addCustomLineItem(category)}
                      className="w-full py-2 border-2 border-dashed border-slate-600 hover:border-orange-500 rounded-lg text-slate-400 hover:text-orange-400 transition-colors flex items-center justify-center space-x-2"
                    >
                      <PlusIcon className="w-4 h-4" />
                      <span className="text-sm">Add Custom Item</span>
                    </button>

                    {/* Category Notes */}
                    <div className="mt-4">
                      <label className="text-sm text-slate-400 mb-2 block">
                        Additional Notes for {category}
                      </label>
                      <textarea
                        value={categoryNotes[category] || ''}
                        onChange={(e) =>
                          setCategoryNotes((prev) => ({
                            ...prev,
                            [category]: e.target.value,
                          }))
                        }
                        className="w-full bg-slate-700 px-3 py-2 rounded text-sm text-white"
                        rows={2}
                        placeholder="Any special requirements, materials, or details..."
                      />
                    </div>
                  </div>
                </div>
              );
            })}
          </div>

          {/* RIGHT PANEL - Summary (Read-Only) */}
          <div className="col-span-3 space-y-4">
            <div className="bg-slate-800/50 backdrop-blur-sm rounded-xl border border-slate-700 p-6 sticky top-24">
              <h2 className="text-lg font-bold text-white mb-4 flex items-center">
                <CheckCircleIcon className="w-5 h-5 mr-2 text-green-400" />
                Proposal Summary
              </h2>

              <div className="space-y-4">
                {/* Category Breakdown */}
                <div className="space-y-2">
                  {categories.map((category) => {
                    const categoryTotal = lineItems
                      .filter((item) => item.category === category)
                      .reduce(
                        (sum, item) => sum + item.quantity * item.pricePerUnit,
                        0
                      );

                    return (
                      <div
                        key={category}
                        className="flex justify-between text-sm"
                      >
                        <span className="text-slate-400">{category}</span>
                        <span className="text-white font-medium">
                          ₹{categoryTotal.toLocaleString('en-IN')}
                        </span>
                      </div>
                    );
                  })}
                </div>

                <div className="border-t border-slate-600 pt-4 space-y-2">
                  <div className="flex justify-between text-sm">
                    <span className="text-slate-400">Subtotal</span>
                    <span className="text-white font-medium">
                      ₹{calculateSubtotal().toLocaleString('en-IN')}
                    </span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span className="text-slate-400">GST (18%)</span>
                    <span className="text-white font-medium">
                      ₹{calculateGST().toLocaleString('en-IN')}
                    </span>
                  </div>
                  <div className="flex justify-between text-lg font-bold border-t border-slate-600 pt-2">
                    <span className="text-white">Total</span>
                    <span className="text-orange-400">
                      ₹{calculateTotal().toLocaleString('en-IN')}
                    </span>
                  </div>
                </div>

                <div className="bg-blue-500/10 border border-blue-500/30 rounded-lg p-3 mt-4">
                  <p className="text-xs text-blue-300">
                    💡 <strong>Auto-generated items</strong> are based on client
                    requirements. You can edit quantities, prices, or remove
                    them.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
